_welcome:
    pattern:  /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: get_notes
        permanent: true # this for 301
_login:
    pattern:  /login
    defaults:
        _controller: AppBundle:Security:login
        route: login


_demo_product:
    resource: "@AppBundle/Controller/ProductController.php"
    type:     rest

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler


_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
_loginCheck:
    pattern:  /loginCheck
    defaults:
        _controller: AppBundle:Security:logincheck
        route: logincheck

_logout:
    pattern: /logout
