AppBundle\Entity\users:
    type: entity
    table: null
    repositoryClass: AppBundle\Entity\usersRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: 255
        email:
            type: string
            length: 255
        password:
            type: string
            length: 255
        role:
            type: string
            length: 255
        createddate:
            type: datetime
    lifecycleCallbacks: {  }
